on:
  workflow_dispatch:
  push:
    branches: ["master"]
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Build"
        run: |
          npm install --quiet --no-progress --cache=.cache/npm
          gulp --lint
          gulp --bundle

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ui-bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
